<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Icons\EditHandleSetTool.png" />
    <None Remove="Resources\Icons\EditShapeTool.png" />
    <None Remove="Resources\Icons\RulerTool.png" />
    <None Remove="Resources\Icons\SelectionTool.png" />
    <None Remove="Resources\Icons\ShapeTool.png" />
    <None Remove="Resources\Icons\TextTool.png" />
    <None Remove="Resources\Icons\testicon.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UI\Dialogs\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Canvases\Tools\Actions\PolygonSheetElementEditActionSet.cs" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\EditHandleSetTool.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Icons\EditShapeTool.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Icons\RulerTool.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Icons\SelectionTool.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Icons\ShapeTool.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Icons\TextTool.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
  </ItemGroup>

</Project>
